---
# main
allowed_hosts: '*'
authentication:
  user: 'foreman'
  password: 'foreman'
  realm: 'foreman'
allowed_items:
  - 'domains'
  - 'environments'
  - 'fact_values'
  - 'hosts'
  - 'hostgroups'
  - 'puppetclasses'
  - 'smart_proxies'
  - 'subnets'
  - 'organizations'
# foreman service
foreman:
  host: localhost
  port: 8233
  scheme: https
  cafile: 'ssl/ca_chain.pem'
  sslverify: False
  user: 'foreman'
  password: 'foreman'
# cache
cache:
  ttl: 3600
  auto_refresh: true
